In [ ]:
import cv2
print(cv2.__version__)

In [15]:
import numpy as np
print(np.__version__)

1.18.5


In [16]:
import cv2
import numpy as np

image = cv2.imread('input.jpg')
cv2.imshow('Figura', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
import cv2 

input = cv2.imread('input.jpg')

cv2.imshow('Hello World', input)
cv2.waitKey()
cv2.destroyAllWindows()

# Simply use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite('output.jpg', input)


True

In [17]:
# Import numpy
import numpy as np

input = cv2.imread('img/input.jpg')
print(input.shape)

#Shape gives the dimensions of the image array
# Let's print each dimension of the image
print('Height of Image:')
print(int(input.shape[0]))
print('Width of Image:')
print(int(input.shape[1]))

(830, 1245, 3)
Height of Image:
830
Width of Image:
1245


In [19]:
print(input)

[[[12 18 31]
  [12 18 31]
  [11 17 30]
  ...
  [21 24 38]
  [21 24 38]
  [21 24 38]]

 [[12 18 31]
  [12 18 31]
  [12 18 31]
  ...
  [21 24 38]
  [21 24 38]
  [21 24 38]]

 [[12 18 31]
  [12 18 31]
  [12 18 31]
  ...
  [21 24 38]
  [21 24 38]
  [21 24 38]]

 ...

 [[ 4  7 12]
  [ 4  7 12]
  [ 3  7 12]
  ...
  [18 23 38]
  [19 24 39]
  [20 25 40]]

 [[ 3  6 11]
  [ 3  6 11]
  [ 3  6 11]
  ...
  [18 23 38]
  [19 24 39]
  [20 25 40]]

 [[ 3  6 11]
  [ 3  6 11]
  [ 2  5 10]
  ...
  [18 23 38]
  [18 23 38]
  [19 24 39]]]
